import type {
  CustomFieldDef,
  DateBucket,
  FilterCondition,
  FilterOp,
  FilterState,
  FieldList,
  GroupColumns,
  GroupState,
  NonWorkingDays,
  PriorityConfig,
  PriorityIconSet,
  Project,
  ProjectConfig,
  SavedView,
  SortRule,
  StatusConfig,
  Task,
  ViewFields,
  ViewMode
} from '../types'
import {
  CUSTOM_FIELD_TYPES,
  DEFAULT_PALETTE_COLOR,
  DEFAULT_PROJECT_COLOR,
  FILTER_OPS,
  GANTT_GRANULARITIES,
  makeDefaultGroup,
  makeDefaultSort,
  MAX_SORT_RULES,
  makeTask,
  PRIORITY_ICON_SETS,
  SORT_KEYS
} from '../types'
import { readColor } from '../utils'
import { t } from '../i18n'
import { stripAutoGeneratedContent, stripProjectAutoContent } from './YamlParser'

/**
 * Frontmatter is hand-editable, so a list of names or ids can hold anything YAML allows.
 * Numbers are kept as their text; a mapping or a null has no name to show and is dropped.
 */
export function stringList(raw: unknown): string[] {
  if (!Array.isArray(raw)) return []
  const values: string[] = []
  for (const entry of raw) {
    if (typeof entry === 'string') {
      if (entry.trim()) values.push(entry)
    } else if (typeof entry === 'number' && Number.isFinite(entry)) values.push(String(entry))
  }
  return values
}

/** Entries without a usable id are dropped; a bad type falls back to free text. */
export function customFieldList(raw: unknown): CustomFieldDef[] {
  if (!Array.isArray(raw)) return []
  const fields: CustomFieldDef[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const f = entry as Partial<CustomFieldDef>
    if (typeof f.id !== 'string' || !f.id) continue
    const field: CustomFieldDef = {
      id: f.id,
      name: typeof f.name === 'string' ? f.name : f.id,
      type: CUSTOM_FIELD_TYPES.includes(f.type as CustomFieldDef['type']) ? (f.type as CustomFieldDef['type']) : 'text'
    }
    const options = stringList(f.options)
    if (options.length) field.options = options
    if (typeof f.icon === 'string' && f.icon) field.icon = f.icon
    if (f.filterable === false) field.filterable = false
    fields.push(field)
  }
  return fields
}

const DATE_BUCKETS: DateBucket[] = ['overdue', 'today', 'this-week', 'this-month']

/** A `between` keeps both of its ends in place, an open end included. */
function conditionValue(raw: unknown, op: FilterOp): FilterCondition['value'] {
  if (typeof raw === 'string') return raw
  if (!Array.isArray(raw)) return undefined
  const isNumber = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v)
  if (raw.some(isNumber) && raw.every((v) => isNumber(v) || (op === 'between' && v === null))) {
    return raw as (number | null)[]
  }
  if (op === 'between') return raw.map((v) => (typeof v === 'string' ? v : ''))
  return stringList(raw)
}

/**
 * Reads a saved filter. Before conditions, a filter was a fixed set of facets plus search
 * text; those become the conditions they meant, and the text a "title contains" condition.
 */
export function hydrateFilter(raw: unknown): FilterState {
  const r = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {}
  const filter: FilterState = { conditions: [], showArchived: r.showArchived === true }
  if (Array.isArray(r.conditions)) {
    for (const entry of r.conditions) {
      if (!entry || typeof entry !== 'object') continue
      const c = entry as Record<string, unknown>
      if (typeof c.field !== 'string' || !c.field) continue
      const op = FILTER_OPS.find((known) => known === c.op)
      if (!op) continue
      const value = conditionValue(c.value, op)
      filter.conditions.push(value === undefined ? { field: c.field, op } : { field: c.field, op, value })
    }
    return filter
  }
  const facets: [string, string][] = [
    ['statuses', 'status'],
    ['priorities', 'priority'],
    ['assignees', 'assignee'],
    ['tags', 'tag']
  ]
  for (const [key, field] of facets) {
    const values = stringList(r[key])
    if (values.length) filter.conditions.push({ field, op: 'any', value: values })
  }
  if (r.dueDateFilter === 'no-date') filter.conditions.push({ field: 'due', op: 'empty' })
  const bucket = DATE_BUCKETS.find((b) => b === r.dueDateFilter)
  if (bucket) filter.conditions.push({ field: 'due', op: 'bucket', value: bucket })
  if (typeof r.text === 'string' && r.text.trim()) {
    filter.conditions.push({ field: 'title', op: 'contains', value: r.text.trim() })
  }
  return filter
}

/**
 * Reads a sort list from `record.sort`. A view saved before sorts had several keys held
 * one `sortKey` / `sortDir` pair instead, which becomes a list of one.
 */
export function hydrateSort(record: Record<string, unknown>): SortRule[] {
  if (Array.isArray(record.sort)) {
    const rules: SortRule[] = []
    for (const entry of record.sort) {
      if (!entry || typeof entry !== 'object') continue
      const r = entry as Record<string, unknown>
      const key = SORT_KEYS.find((k) => k === r.key)
      if (!key || rules.some((rule) => rule.key === key)) continue
      rules.push({ key, dir: r.dir === 'desc' ? 'desc' : 'asc' })
    }
    return rules.slice(0, MAX_SORT_RULES)
  }
  const key = SORT_KEYS.find((k) => k === record.sortKey)
  if (!key) return makeDefaultSort()
  return [{ key, dir: record.sortDir === 'desc' ? 'desc' : 'asc' }]
}

export function hydrateGroup(raw: unknown): GroupState {
  const r = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {}
  const group: GroupState = typeof r.field === 'string' && r.field ? { field: r.field } : makeDefaultGroup()
  if (r.hideEmpty === true) group.hideEmpty = true
  if (r.columns && typeof r.columns === 'object') {
    const columns: Record<string, GroupColumns> = {}
    for (const [field, value] of Object.entries(r.columns as Record<string, unknown>)) {
      if (!value || typeof value !== 'object') continue
      const v = value as Record<string, unknown>
      const entry: GroupColumns = {}
      if (Array.isArray(v.order)) entry.order = v.order.filter((id): id is string => typeof id === 'string')
      if (Array.isArray(v.hidden)) entry.hidden = v.hidden.filter((id): id is string => typeof id === 'string')
      if (entry.order || entry.hidden) columns[field] = entry
    }
    if (Object.keys(columns).length) group.columns = columns
  }
  return group
}

const FIELD_MODES: ViewMode[] = ['table', 'gantt', 'kanban']

export function hydrateFields(raw: unknown): ViewFields {
  const r = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {}
  const fields: ViewFields = {}
  for (const mode of FIELD_MODES) {
    const entry = r[mode]
    if (!entry || typeof entry !== 'object') continue
    const e = entry as Record<string, unknown>
    if (!Array.isArray(e.visible)) continue
    const list: FieldList = { visible: e.visible.filter((id): id is string => typeof id === 'string') }
    if (e.widths && typeof e.widths === 'object') {
      const widths = Object.entries(e.widths as Record<string, unknown>).filter(
        (pair): pair is [string, number] => typeof pair[1] === 'number' && Number.isFinite(pair[1]) && pair[1] > 0
      )
      if (widths.length) list.widths = Object.fromEntries(widths.map(([id, px]) => [id, Math.round(px)]))
    }
    fields[mode] = list
  }
  return fields
}

export function hydrateNonWorkingDays(raw: unknown): NonWorkingDays {
  const r = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {}
  const days: NonWorkingDays = {}
  if (r.weekends === true) days.weekends = true
  if (r.holidays === true) days.holidays = true
  return days
}

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const viewMode = v.viewMode
      const validViewMode: ViewMode | undefined =
        viewMode === 'table' || viewMode === 'gantt' || viewMode === 'kanban' ? viewMode : undefined
      const granularity = GANTT_GRANULARITIES.find((g) => g === v.ganttGranularity)
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? t('common.untitled'),
        filter: hydrateFilter(v.filter),
        sort: hydrateSort(v),
        ...(v.group ? { group: hydrateGroup(v.group) } : {}),
        ...(v.fields ? { fields: hydrateFields(v.fields) } : {}),
        ...(validViewMode ? { viewMode: validViewMode } : {}),
        ...(granularity ? { ganttGranularity: granularity } : {}),
        ...(v.nonWorkingDays ? { nonWorkingDays: hydrateNonWorkingDays(v.nonWorkingDays) } : {}),
        ...(v.isDefault === true ? { isDefault: true } : {})
      }
    })
}

export function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  return makeTask({
    id: r.id as string,
    title: (r.title as string) ?? t('common.untitled'),
    description: (r.description as string) ?? '',
    type: (r.type as string) === 'milestone' ? 'milestone' : (r.type as string) === 'subtask' ? 'subtask' : 'task',
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    completed: (r.completed as string) ?? '',
    // On the metadataCache path `r` is Obsidian's live frontmatter object, so these
    // containers are copied, not aliased: sharing them would let an edit corrupt the cache.
    assignees: stringList(r.assignees),
    tags: stringList(r.tags),
    subtasks: [],
    dependencies: stringList(r.dependencies),
    recurrence:
      r.recurrence && typeof r.recurrence === 'object'
        ? ({ ...(r.recurrence as Task['recurrence']) } as Task['recurrence'])
        : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs)
      ? (r.timeLogs as { date: string; hours: number; note: string }[]).map((log) => ({ ...log }))
      : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null
        ? { ...(r.customFields as Record<string, unknown>) }
        : {},
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : []
    })
  })
}

export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  const task = mapRawToTask(frontmatter, {
    description: stripAutoGeneratedContent(body),
    filePath
  })
  const subtaskIds = stringList(frontmatter.subtaskIds)
  const parentId = typeof frontmatter.parentId === 'string' && frontmatter.parentId ? frontmatter.parentId : null
  return { task, subtaskIds, parentId }
}

/** The note's prose. A `description` property is read only from notes written before that. */
export function projectDescription(frontmatter: Record<string, unknown>, body: string): string {
  const prose = stripProjectAutoContent(body)
  if (prose) return prose
  return typeof frontmatter.description === 'string' ? frontmatter.description : ''
}

export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: projectDescription(frontmatter, body),
    color: readColor(frontmatter.color) ?? DEFAULT_PROJECT_COLOR,
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    customFields: customFieldList(frontmatter.customFields),
    teamMembers: stringList(frontmatter.teamMembers),
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
    config: hydrateProjectConfig(frontmatter.config),
    ...(frontmatter.archived === true ? { archived: true } : {}),
    taskIndex: new Map()
  }
}

/** Drops malformed fields. Absent or empty means inherit everything. */
function hydrateProjectConfig(raw: unknown): ProjectConfig | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const config: ProjectConfig = {}
  const statuses = hydrateStatusList(r.statuses)
  if (statuses) config.statuses = statuses
  const priorities = hydratePriorityList(r.priorities)
  if (priorities) config.priorities = priorities
  if (typeof r.priorityIcons === 'string' && r.priorityIcons in PRIORITY_ICON_SETS) {
    config.priorityIcons = r.priorityIcons as PriorityIconSet
  }
  const hidden = stringList(r.hiddenCustomFields)
  if (hidden.length) config.hiddenCustomFields = hidden
  if (r.defaultView === 'table' || r.defaultView === 'gantt' || r.defaultView === 'kanban') {
    config.defaultView = r.defaultView
  }
  if (typeof r.autoSchedule === 'boolean') config.autoSchedule = r.autoSchedule
  if (typeof r.pullForwardOnEarlyFinish === 'boolean') config.pullForwardOnEarlyFinish = r.pullForwardOnEarlyFinish
  if (typeof r.autoArchiveDays === 'number' && Number.isFinite(r.autoArchiveDays) && r.autoArchiveDays >= 0) {
    config.autoArchiveDays = Math.floor(r.autoArchiveDays)
  }
  if (typeof r.showSubtreeConnections === 'boolean') config.showSubtreeConnections = r.showSubtreeConnections
  if (
    r.lineBorders === 'none' ||
    r.lineBorders === 'horizontal' ||
    r.lineBorders === 'vertical' ||
    r.lineBorders === 'both'
  ) {
    config.lineBorders = r.lineBorders
  }
  return Object.keys(config).length ? config : undefined
}

function hydrateStatusList(raw: unknown): StatusConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const statuses: StatusConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const s = entry as Partial<StatusConfig>
    if (typeof s.id !== 'string' || !s.id) continue
    statuses.push({
      id: s.id,
      label: typeof s.label === 'string' ? s.label : s.id,
      color: readColor(s.color) ?? DEFAULT_PALETTE_COLOR,
      icon: typeof s.icon === 'string' ? s.icon : '',
      complete: s.complete === true
    })
  }
  return statuses.length ? statuses : undefined
}

function hydratePriorityList(raw: unknown): PriorityConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const priorities: PriorityConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const p = entry as Partial<PriorityConfig>
    if (typeof p.id !== 'string' || !p.id) continue
    priorities.push({
      id: p.id,
      label: typeof p.label === 'string' ? p.label : p.id,
      color: readColor(p.color) ?? DEFAULT_PALETTE_COLOR,
      icon: typeof p.icon === 'string' ? p.icon : ''
    })
  }
  return priorities.length ? priorities : undefined
}
