import { describe, expect, it } from 'vitest'
import { appendYaml, isOldFormat, parseFrontmatter, stripAutoGeneratedContent } from './YamlParser'

describe('parseFrontmatter', () => {
  it('reports no frontmatter when the document has no fences', () => {
    const parsed = parseFrontmatter('just body text')
    expect(parsed).toEqual({ kind: 'none', body: 'just body text' })
  })

  it('parses a fenced frontmatter block', () => {
    const doc = '---\ntitle: "Hello"\ncount: 3\n---\n\n# Body'
    const parsed = parseFrontmatter(doc)
    expect(parsed).toEqual({ kind: 'frontmatter', frontmatter: { title: 'Hello', count: 3 }, body: '# Body' })
  })

  it('reports no frontmatter, keeping the full content as body, when the closing fence is missing', () => {
    const doc = '---\ntitle: "Hello"\n'
    expect(parseFrontmatter(doc)).toEqual({ kind: 'none', body: doc })
  })

  it('reports malformed, and no body, when the block will not parse', () => {
    const parsed = parseFrontmatter('---\n: : :\n---\nbody')
    expect(parsed).toEqual({ kind: 'malformed' })
  })

  it('reads a block written with carriage returns', () => {
    const doc = '---\r\ntitle: "Hello"\r\ntags: []\r\n---\r\n\r\n# Body\r\n'
    expect(parseFrontmatter(doc)).toEqual({
      kind: 'frontmatter',
      frontmatter: { title: 'Hello', tags: [] },
      body: '# Body'
    })
  })

  it('reads an empty block as a note with no properties', () => {
    expect(parseFrontmatter('---\n\n---\n\n# Body')).toEqual({ kind: 'frontmatter', frontmatter: {}, body: '# Body' })
  })

  it('reports no frontmatter when the opening fence carries other text', () => {
    const doc = '----\nnot frontmatter\n----\n'
    expect(parseFrontmatter(doc)).toEqual({ kind: 'none', body: doc })
  })
})

describe('stripAutoGeneratedContent', () => {
  it('removes Project wiki-link lines', () => {
    expect(stripAutoGeneratedContent('Project: [[my-project|My Project]]')).toBe('')
  })

  it('removes Parent wiki-link lines', () => {
    expect(stripAutoGeneratedContent('Parent: [[parent-slug|Parent]]')).toBe('')
  })

  it('removes a trailing Subtasks section', () => {
    const body = 'Description goes here\n\n## Subtasks\n- [ ] [[sub|Sub]]'
    expect(stripAutoGeneratedContent(body)).toBe('Description goes here')
  })

  it('preserves user content when no auto-generated markers exist', () => {
    expect(stripAutoGeneratedContent('Plain description.')).toBe('Plain description.')
  })
})

describe('isOldFormat', () => {
  it('is true when tasks is a non-empty array and taskIds is absent', () => {
    expect(isOldFormat({ tasks: [{ id: 'a' }] })).toBe(true)
  })

  it('is false when taskIds is present even if tasks is also set', () => {
    expect(isOldFormat({ tasks: [{ id: 'a' }], taskIds: ['a'] })).toBe(false)
  })

  it('is false when tasks is empty', () => {
    expect(isOldFormat({ tasks: [] })).toBe(false)
  })

  it('is false when tasks is absent', () => {
    expect(isOldFormat({ title: 'Project' })).toBe(false)
  })
})

describe('appendYaml', () => {
  it('serializes primitive types with quoted strings and unquoted numbers/bools', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'hi', n: 2, b: true, nil: null }, 0)
    expect(lines).toEqual(['s: "hi"', 'n: 2', 'b: true', 'nil:'])
  })

  it('escapes quotes, backslashes, and newlines in strings', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'a "b"\n\\c' }, 0)
    expect(lines).toEqual(['s: "a \\"b\\"\\n\\\\c"'])
  })

  it('emits inline arrays for primitive items and empty arrays as []', () => {
    const lines: string[] = []
    appendYaml(lines, { list: ['a', 'b'], empty: [] }, 0)
    expect(lines).toEqual(['list: ["a", "b"]', 'empty: []'])
  })

  it('emits nested blocks for arrays of objects', () => {
    const lines: string[] = []
    appendYaml(
      lines,
      {
        items: [
          { k: 'v1', n: 1 },
          { k: 'v2', n: 2 }
        ]
      },
      0
    )
    expect(lines).toEqual(['items:', '  - k: "v1"', '    n: 1', '  - k: "v2"', '    n: 2'])
  })

  it('indents nested objects by the given amount', () => {
    const lines: string[] = []
    appendYaml(lines, { outer: { inner: 'x' } }, 0)
    expect(lines).toEqual(['outer:', '  inner: "x"'])
  })
})
