import { stringifyYaml } from '../yaml'
import type { Project, ProjectConfig, StatusConfig, Task } from '../types'
import { isTerminalStatus, sanitizeFileName } from '../utils'
import { appendYaml, FRONTMATTER_KEY, stripAutoGeneratedContent, TASK_FRONTMATTER_KEY } from './YamlParser'

/** Writes the wikilinks a note holds, abbreviated against that note's own location. */
export interface RefWriter {
  link(targetPath: string, title: string): string
  /** Null while the task has no note to point at. */
  task(task: Task): string | null
  /** Null when no note in the vault holds that task id. */
  dependency(taskId: string): string | null
}

export const PROJECT_FRONTMATTER_KEYS: ReadonlySet<string> = new Set([
  FRONTMATTER_KEY,
  'id',
  'title',
  'description',
  'color',
  'icon',
  'taskIds',
  'parent',
  'customFields',
  'teamMembers',
  'savedViews',
  'createdAt',
  'updatedAt',
  'config',
  'tasks'
])

export const TASK_FRONTMATTER_KEYS: ReadonlySet<string> = new Set([
  TASK_FRONTMATTER_KEY,
  'projectId',
  'parentId',
  'id',
  'title',
  'description',
  'type',
  'status',
  'priority',
  'start',
  'due',
  'progress',
  'assignees',
  'tags',
  'subtaskIds',
  'dependencies',
  'createdAt',
  'updatedAt',
  'completed',
  'recurrence',
  'timeEstimate',
  'timeLogs',
  'customFields',
  // Written by older versions; owned so a save drops it.
  'collapsed'
])

export function foreignFrontmatter(
  frontmatter: Record<string, unknown> | null,
  owned: ReadonlySet<string>
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  if (!frontmatter) return out
  for (const [key, value] of Object.entries(frontmatter)) {
    if (!owned.has(key)) out[key] = value
  }
  return out
}

function appendForeignYaml(lines: string[], foreign: Record<string, unknown>): void {
  if (Object.keys(foreign).length) lines.push(stringifyYaml(foreign).trimEnd())
}

/** Only fields the project actually overrides; an empty block is omitted entirely. */
function serializeProjectConfig(config: ProjectConfig | undefined): Record<string, unknown> | null {
  if (!config) return null
  const out: Record<string, unknown> = {}
  if (config.statuses?.length) out.statuses = config.statuses
  if (config.priorities?.length) out.priorities = config.priorities
  if (config.priorityIcons) out.priorityIcons = config.priorityIcons
  if (config.hiddenCustomFields?.length) out.hiddenCustomFields = config.hiddenCustomFields
  if (config.defaultView) out.defaultView = config.defaultView
  if (config.autoSchedule !== undefined) out.autoSchedule = config.autoSchedule
  if (config.pullForwardOnEarlyFinish !== undefined) out.pullForwardOnEarlyFinish = config.pullForwardOnEarlyFinish
  if (config.autoArchiveDays !== undefined) out.autoArchiveDays = config.autoArchiveDays
  if (config.showSubtreeConnections !== undefined) out.showSubtreeConnections = config.showSubtreeConnections
  if (config.lineBorders) out.lineBorders = config.lineBorders
  if (config.kanbanShowSubtasks !== undefined) out.kanbanShowSubtasks = config.kanbanShowSubtasks
  if (config.kanbanShowDescriptionPreview !== undefined) {
    out.kanbanShowDescriptionPreview = config.kanbanShowDescriptionPreview
  }
  return Object.keys(out).length ? out : null
}

export function serializeProject(
  project: Project,
  statuses: StatusConfig[],
  refs: RefWriter,
  foreign: Record<string, unknown> = {}
): string {
  const seen = new Set<string>()
  const tasks: Task[] = []
  for (const t of project.tasks) {
    if (seen.has(t.id)) continue
    seen.add(t.id)
    tasks.push(t)
  }
  const taskIds = tasks.map((t) => refs.task(t) ?? t.id)

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    ...(project.parentPath ? { parent: `[[${project.parentPath.replace(/\.md$/, '')}]]` } : {}),
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt
  }
  const config = serializeProjectConfig(project.config)
  if (config) fm.config = config

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  appendForeignYaml(yamlLines, foreign)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${project.icon} ${project.title}`)
  yamlLines.push('')
  if (project.description) {
    yamlLines.push(project.description)
    yamlLines.push('')
  }
  if (tasks.length) {
    yamlLines.push('## Tasks')
    for (const t of tasks) {
      if (t.filePath) {
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' '
        yamlLines.push(`- [${check}] ${refs.link(t.filePath, t.title)}`)
      }
    }
    yamlLines.push('')
  }

  return yamlLines.join('\n')
}

export function buildTaskFrontmatter(
  task: Task,
  project: Project,
  parentTask: Task | null,
  refs: RefWriter
): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: refs.link(project.filePath, project.title),
    parentId: parentTask ? (refs.task(parentTask) ?? parentTask.id) : null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds: task.subtasks.map((s) => refs.task(s) ?? s.id),
    dependencies: task.dependencies.map((id) => refs.dependency(id) ?? id),
    createdAt: task.createdAt,
    updatedAt: task.updatedAt
  }
  if (task.completed) fm.completed = task.completed
  if (task.recurrence) fm.recurrence = task.recurrence
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields
  return fm
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[],
  refs: RefWriter,
  foreign: Record<string, unknown> = {}
): string {
  const fm = buildTaskFrontmatter(task, project, parentTask, refs)

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  appendForeignYaml(yamlLines, foreign)
  yamlLines.push('---')
  yamlLines.push('')
  const cleanDesc = stripAutoGeneratedContent(task.description)
  if (cleanDesc) {
    yamlLines.push(cleanDesc)
    yamlLines.push('')
  }

  const parentLink = parentTask ? refs.task(parentTask) : null
  if (parentLink) {
    yamlLines.push(`Parent: ${parentLink}`)
  } else {
    yamlLines.push(`Project: ${refs.link(project.filePath, project.title)}`)
  }

  if (task.subtasks.length) {
    yamlLines.push('')
    yamlLines.push('## Subtasks')
    for (const sub of task.subtasks) {
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' '
      const link = refs.task(sub) ?? `[[${taskSlug(sub.title)}|${sub.title}]]`
      yamlLines.push(`- [${check}] ${link}`)
    }
  }

  return yamlLines.join('\n')
}

/** Keeps paths under Windows MAX_PATH and the limits mobile and sync impose. */
export const TASK_SLUG_MAX_LENGTH = 60

function taskSlug(title: string): string {
  return sanitizeFileName(title).toLowerCase().replace(/\s+/g, '-').slice(0, TASK_SLUG_MAX_LENGTH)
}

export function taskFilePath(taskTitle: string, folder: string): string {
  return `${folder}/${taskSlug(taskTitle)}.md`
}
