import { parseYaml } from '../yaml'

export const FRONTMATTER_KEY = 'pm-project'
export const TASK_FRONTMATTER_KEY = 'pm-task'

/**
 * 'none' is a note without frontmatter, so its whole content is the body, matching
 * how Obsidian reads a note that opens with a horizontal rule. 'malformed' carries
 * neither: a note whose frontmatter block will not parse has no readable body, and
 * callers must not fall back to its content.
 */
export type ParsedFrontmatter =
  | { kind: 'frontmatter'; frontmatter: Record<string, unknown>; body: string }
  | { kind: 'none'; body: string }
  | { kind: 'malformed' }

const FRONTMATTER_BLOCK = /^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/

const toLf = (text: string): string => text.replace(/\r\n/g, '\n')

export function parseFrontmatter(content: string): ParsedFrontmatter {
  const block = FRONTMATTER_BLOCK.exec(content)
  if (!block) return { kind: 'none', body: toLf(content) }
  let parsed: unknown
  try {
    parsed = parseYaml(toLf(block[1]))
  } catch {
    return { kind: 'malformed' }
  }
  // An empty or non-mapping block is a note carrying no properties, not a broken one.
  const frontmatter =
    parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed) ? (parsed as Record<string, unknown>) : {}
  return { kind: 'frontmatter', frontmatter, body: toLf(content.slice(block[0].length)).trim() }
}

/** Without this the generated wiki-link lines would be duplicated on every save. */
export function stripAutoGeneratedContent(body: string): string {
  let result = body
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '')
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '')
  result = result.replace(/\n## Subtasks[\s\S]*$/, '')
  return result.trim()
}

export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent)
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`)
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r/g, '\\r').replace(/\n/g, '\\n')
      lines.push(`${pad}${key}: "${escaped}"`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`)
      } else if (typeof val[0] === 'object') {
        lines.push(`${pad}${key}:`)
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>)
          if (entries.length === 0) continue
          const [firstKey, firstVal] = entries[0]
          lines.push(`${pad}  - ${firstKey}: ${JSON.stringify(firstVal)}`)
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${k}: ${JSON.stringify(v)}`)
          }
        }
      } else {
        const items = val.map((v) => JSON.stringify(v)).join(', ')
        lines.push(`${pad}${key}: [${items}]`)
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val)
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`)
      } else {
        lines.push(`${pad}${key}:`)
        appendYaml(lines, val as Record<string, unknown>, indent + 1)
      }
    }
  }
}

export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0 && !Array.isArray(frontmatter.taskIds)
}
